### PR TITLE
Add Oh My Zsh support

### PR DESCRIPTION
**Pull request by xoob**
This PR allows to auto-completion to be installed as a plugin of oh-my-zsh. It's done by satisfying the `is_plugin()` check in https://github.com/robbyrussell/oh-my-zsh/blob/master/oh-my-zsh.sh#L38.

### CODE REVIEW

**Comment by Jaganpro** [comment]
Hi xoob, i tried to follow the instructions and still no luck with Autocomplete with Oh My Zsh.

My .zhrc file
image

My Custom Plugin Folder
image

Not sure what i am missing!

**Comment by xoob** [comment]
@jaganpro maybe because this isn’t merged yet. Can you try pulling from my fork, like so:

```console
git clone git@github.com:xoob/salesforce-cli-zsh-completion.git ~/.oh-my-zsh/custom/plugins/salesforce-cli-zsh-completion
```

**Comment by Jaganpro** [comment]
@xoob , Thank you! This is a great find. 
For some reason, even though i cloned from your repo, "salesforce-cli-zsh-completion.plugin.zsh" file was not created. 

I manually created this shell file by using "touch salesforce-cli-zsh-completion.plugin.zsh" and it started working!

@wadewegner  Thank you! I love SFDX CLI even more!

**Comment by xoob** [comment]
@jaganpro One more idea, try `git checkout new/oh-my-zsh` to switch to my branch with the changes.

**Pull request merged**
